name: Create PR from leetcode-sync (keep README)

on:
  push:
    branches: [leetcode-sync]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: leetcode-sync
          fetch-depth: 0

      - name: Fetch main to get its README
        run: |
          git fetch origin main
          mkdir -p tmp
          (git show origin/main:README.md > tmp/README.md) || true

      - name: Replace README in working tree with main's version
        run: |
          if [ -f tmp/README.md ]; then
            mv tmp/README.md README.md
          else
            rm -f README.md || true
          fi

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Sync from leetcode-sync (keep README from main)"
          title: "Sync: leetcode-sync → main (keep README)"
          body: "Auto-sync from leetcode-sync. README.md kept from main."
          branch: sync/pr-keep-readme
          base: main
          labels: auto-sync
          delete-branch: true
